global:
  scrape_interval: 15s  # Intervalle de collecte des métriques

scrape_configs:
  - job_name: 'my_app'
    static_configs:
      - targets: ['localhost:8080']  # Remplacez par vos cibles

