# Utilisez une image officielle Python comme base
FROM python:3.8-slim


# RUN apt-get update && apt-get install -y \
#     ca-certificates \
#     curl \
#     gnupg \
#     && curl -sSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | tee /etc/apt/trusted.gpg.d/pgdg.asc \
#     && echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -c | awk '{print $2}')-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
#     && apt-get update \
#     && apt-get install -y postgresql-14 postgresql-client-14 git \
#     && rm -rf /var/lib/apt/lists/*

WORKDIR /app
WORKDIR /tmp

RUN cd /app

RUN apt-get update && apt-get install -y \
    postgresql \
    postgresql-contrib \
    git \
    && rm -rf /var/lib/apt/lists/*

# Cloner le dépôt pgvector
RUN cd /tmp \
    git clone --branch v0.7.4 https://github.com/pgvector/pgvector.git  \
    cd pgvector  \
    make  \
    make install # may need sudo  \
    rm -rf /tmp/pgvector \
    cd ..

WORKDIR /app

RUN cd /app

# Copiez le reste des fichiers de l'application dans le répertoire de travail
COPY . .

RUN ls

# Installez les dépendances de l'application
RUN pip install  -r requirements.txt 
#--no-cache-dir


# Exposer la port 8001
EXPOSE 8001

# lancement de l'api 
CMD ["python", "Apidb.py"]

