FROM postgres:latest

# Mettre à jour les dépendances
# RUN apt-get update && apt-get install -y \
#     build-essential \
#     git \
#     postgresql-server-dev-all \
#     && rm -rf /var/lib/apt/lists/*

# # Cloner le dépôt pgvector
WORKDIR /tmp
# RUN git clone https://github.com/pgvector/pgvector.git

# Compiler et installer pgvector
# WORKDIR /tmp/pgvector
# RUN make clean && \
#     make OPTFLAGS="" && \
#     make install && \
#     mkdir /usr/share/doc/pgvector && \
#     cp LICENSE README.md /usr/share/doc/pgvector && \
#     rm -rf /tmp/pgvector

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*


RUN cd /tmp \
    git clone --branch v0.7.4 https://github.com/pgvector/pgvector.git  \
    cd pgvector  \
    make  \
    make install # may need sudo  

# Copiez le fichier des dépendances dans le répertoire de travail
COPY requirements.txt .

# Installez les dépendances de l'application
RUN python3-pip install  requirements.txt

# Créer l'extension vector
# RUN echo "CREATE EXTENSION IF NOT EXISTS vector;" | psql -U postgres -d postgres


# Exposer la port 5432
EXPOSE 5432

CMD ["python", "Apidb.py"]



