# Utilisez une image officielle Python comme base
FROM python:3.8-slim

RUN apt-get update && apt-get install -y postgres #git

WORKDIR /app

RUN cd /app

# Copiez le reste des fichiers de l'application dans le répertoire de travail
COPY . .

RUN ls

# Installez les dépendances de l'application
RUN pip install --no-cache-dir -r requirements.txt


# Exposer la port 5432
EXPOSE 5432

# lancement de l'api 
CMD ["python", "Apidb.py"]

