name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      ApiDb_changed: ${{ steps.ApiDb.outputs.changed }}
      ApiWhisper_changed: ${{ steps.ApiWhisper.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changes for ApiDb
        id: ApiDb
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^ApiDb/'; then
            echo "ApiDb changed."
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "ApiDb not changed."
            echo "changed=false" >> $GITHUB_ENV
          fi
        outputs:
          changed: ${{ env.changed }}

      - name: Detect changes for ApiWhisper
        id: ApiWhisper
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^ApiWhisper/'; then
            echo "ApiWhisper changed."
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "ApiWhisper not changed."
            echo "changed=false" >> $GITHUB_ENV
          fi
        outputs:
          changed: ${{ env.changed }}

  test-ApiDb:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.ApiDb_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies for ApiDb
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('ApiDb/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install testing dependencies
        run: |
          pip install pytest pytest-testmon

      - name: Install dependencies for ApiDb
        run: |
          python -m pip install --upgrade pip
          pip install -r ApiDb/requirements.txt

      - name: Run tests for ApiDb
        run: pytest --testmon ApiDb

  test-ApiWhisper:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.ApiWhisper_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies for ApiWhisper
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('ApiWhisper/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies for ApiWhisper
        run: |
          python -m pip install --upgrade pip
          pip install -r ApiWhisper/requirements.txt

      - name: Run tests for ApiWhisper
        run: pytest --testmon ApiWhisper
